In [1]:
import gym
import numpy as np

In [3]:
env = gym.make('Taxi-v2')
action_space = env.action_space.n
state_space  = env.observation_space.n
print("Action Space:", action_space)
print("State Space:", state_space)

Action Space: 6
State Space: 500


In [4]:
Q_table = np.zeros((state_space, action_space))
print(Q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
np.random.randint(5)

3

In [28]:
num_episodes = 50001
num_steps    = 100

discount_rate = 0.7
learning_rate = 0.1

for episode in range(num_episodes):
    print_info = episode % 1000 == 0
    if print_info: print("-- Episode {}/{} --".format(episode, num_episodes))
    
    epsilon = 1 - episode / num_episodes
    total_reward = 0
    
    if print_info: print("Epsilon:", epsilon)
    
    state = env.reset()
    for step in range(num_steps):
        if np.random.rand() > epsilon:
            action = np.argmax(Q_table[state, :])
        else:
            action = np.random.randint(action_space)

        new_state, reward, done, info = env.step(action)
        total_reward += reward

        # Q(s, a) <- Q(s, a) + alpha * [r + gamma * max_a' Q(s', a') - Q(s, a)]
        Q_cur = Q_table[state, action]
        Q_table[state, action] = Q_cur + learning_rate * (reward + discount_rate * np.max(Q_table[new_state, :]) - Q_cur)
        
        state = new_state
        if done: break
    if print_info: print("Total reward:", total_reward)

-- Episode 0/50001 --
Epsilon: 1.0
Total reward: -370
-- Episode 1000/50001 --
Epsilon: 0.9800003999920002
Total reward: -451
-- Episode 2000/50001 --
Epsilon: 0.9600007999840003
Total reward: -334
-- Episode 3000/50001 --
Epsilon: 0.9400011999760005
Total reward: -325
-- Episode 4000/50001 --
Epsilon: 0.9200015999680007
Total reward: -388
-- Episode 5000/50001 --
Epsilon: 0.9000019999600009
Total reward: -370
-- Episode 6000/50001 --
Epsilon: 0.8800023999520009
Total reward: -370
-- Episode 7000/50001 --
Epsilon: 0.8600027999440011
Total reward: -316
-- Episode 8000/50001 --
Epsilon: 0.8400031999360013
Total reward: -361
-- Episode 9000/50001 --
Epsilon: 0.8200035999280014
Total reward: -218
-- Episode 10000/50001 --
Epsilon: 0.8000039999200016
Total reward: -370
-- Episode 11000/50001 --
Epsilon: 0.7800043999120018
Total reward: -253
-- Episode 12000/50001 --
Epsilon: 0.7600047999040019
Total reward: -214
-- Episode 13000/50001 --
Epsilon: 0.740005199896002
Total reward: -307
-- Epis

In [30]:
state = env.reset()
for step in range(num_steps):
    env.render()
    action = np.argmax(Q_table[state, :])
    new_state, reward, done, info = env.step(action)
    state = new_state
    if done:
        print("Victory")
        break

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
|_| : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
|_: : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| :_: : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : :_: : |
| : : : : |
| | : | : |
|Y| : |B: |