In [1]:
import gym
import numpy as np

In [15]:
env = gym.make("CartPole-v0")
action_space = env.action_space.n
state_space = env.observation_space.shape
print("Action space:", action_space)
print("State space:", state_space)

Action space: 2
State space: (4,)


In [17]:
import keras
from keras.models import Model
from keras.layers import Input, Dense
import keras.backend as K

In [20]:
input_state = Input(shape=state_space)
x = Dense(512, activation="elu")(input_state)
x = Dense(64, activation="elu")(x)
action_prob = Dense(action_space, activation="softmax")(x)

def loss(rewards_and_baselines, action_prob):
    R_t = rewards_and_baselines[:, 0]
    b   = rewards_and_baselines[:, 1]
    
    # R_t:         [horizon]
    # b:           [horizon]
    # action_prob: [horizon, action_space]
    return K.sum((R_t - b) * K.log(action_prob))

model = Model(input_state, action_prob)
model.compile(optimizer="SGD", loss=loss)

In [8]:
num_episodes = 1
num_steps = 500

for episode in range(num_episodes):
    state = env.reset()
    for step in range(num_steps):
        env.render()
        
        action_prob = model.predict(np.expand_dims(state, axis=0))
        action = np.argmax(action_prob)
        
        new_state, reward, done, info = env.step(action)
        
        
        print(new_state, reward, done, info)
        if done:
            break
        i += 1

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[-0.03410821 -0.20995339  0.01880013  0.3426508 ] 1.0 False {}
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 25